//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseController.autocad.masterkey.ws {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Firm", Namespace="http://schemas.datacontract.org/2004/07/LicenseControllerWs")]
    [System.SerializableAttribute()]
    public partial class Firm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InsertDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertDate {
            get {
                return this.InsertDateField;
            }
            set {
                if ((this.InsertDateField.Equals(value) != true)) {
                    this.InsertDateField = value;
                    this.RaisePropertyChanged("InsertDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Computer", Namespace="http://schemas.datacontract.org/2004/07/LicenseControllerWs")]
    [System.SerializableAttribute()]
    public partial class Computer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FirmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InsertDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsComputerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsRootMachineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsVisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PyshicalAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirmId {
            get {
                return this.FirmIdField;
            }
            set {
                if ((this.FirmIdField.Equals(value) != true)) {
                    this.FirmIdField = value;
                    this.RaisePropertyChanged("FirmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertDate {
            get {
                return this.InsertDateField;
            }
            set {
                if ((this.InsertDateField.Equals(value) != true)) {
                    this.InsertDateField = value;
                    this.RaisePropertyChanged("InsertDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsComputer {
            get {
                return this.IsComputerField;
            }
            set {
                if ((this.IsComputerField.Equals(value) != true)) {
                    this.IsComputerField = value;
                    this.RaisePropertyChanged("IsComputer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRootMachine {
            get {
                return this.IsRootMachineField;
            }
            set {
                if ((this.IsRootMachineField.Equals(value) != true)) {
                    this.IsRootMachineField = value;
                    this.RaisePropertyChanged("IsRootMachine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVisible {
            get {
                return this.IsVisibleField;
            }
            set {
                if ((this.IsVisibleField.Equals(value) != true)) {
                    this.IsVisibleField = value;
                    this.RaisePropertyChanged("IsVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PyshicalAddress {
            get {
                return this.PyshicalAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PyshicalAddressField, value) != true)) {
                    this.PyshicalAddressField = value;
                    this.RaisePropertyChanged("PyshicalAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operation", Namespace="http://schemas.datacontract.org/2004/07/LicenseControllerWs")]
    [System.SerializableAttribute()]
    public partial class Operation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ComputerCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LicenseController.autocad.masterkey.ws.Firm FirmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FirmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComputerCount {
            get {
                return this.ComputerCountField;
            }
            set {
                if ((this.ComputerCountField.Equals(value) != true)) {
                    this.ComputerCountField = value;
                    this.RaisePropertyChanged("ComputerCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LicenseController.autocad.masterkey.ws.Firm Firm {
            get {
                return this.FirmField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmField, value) != true)) {
                    this.FirmField = value;
                    this.RaisePropertyChanged("Firm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirmId {
            get {
                return this.FirmIdField;
            }
            set {
                if ((this.FirmIdField.Equals(value) != true)) {
                    this.FirmIdField = value;
                    this.RaisePropertyChanged("FirmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckLicense", Namespace="http://schemas.datacontract.org/2004/07/LicenseControllerWs")]
    [System.SerializableAttribute()]
    public partial class CheckLicense : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AppIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CheckDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ComputerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FirmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> InstallDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> InstalledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsFoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OperationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UnInstallDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> UninstalledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UpdateDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((this.AppIdField.Equals(value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CheckDate {
            get {
                return this.CheckDateField;
            }
            set {
                if ((this.CheckDateField.Equals(value) != true)) {
                    this.CheckDateField = value;
                    this.RaisePropertyChanged("CheckDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ComputerId {
            get {
                return this.ComputerIdField;
            }
            set {
                if ((this.ComputerIdField.Equals(value) != true)) {
                    this.ComputerIdField = value;
                    this.RaisePropertyChanged("ComputerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FirmId {
            get {
                return this.FirmIdField;
            }
            set {
                if ((this.FirmIdField.Equals(value) != true)) {
                    this.FirmIdField = value;
                    this.RaisePropertyChanged("FirmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InstallDate {
            get {
                return this.InstallDateField;
            }
            set {
                if ((this.InstallDateField.Equals(value) != true)) {
                    this.InstallDateField = value;
                    this.RaisePropertyChanged("InstallDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Installed {
            get {
                return this.InstalledField;
            }
            set {
                if ((this.InstalledField.Equals(value) != true)) {
                    this.InstalledField = value;
                    this.RaisePropertyChanged("Installed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsFound {
            get {
                return this.IsFoundField;
            }
            set {
                if ((this.IsFoundField.Equals(value) != true)) {
                    this.IsFoundField = value;
                    this.RaisePropertyChanged("IsFound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineName {
            get {
                return this.MachineNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineNameField, value) != true)) {
                    this.MachineNameField = value;
                    this.RaisePropertyChanged("MachineName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OperationId {
            get {
                return this.OperationIdField;
            }
            set {
                if ((this.OperationIdField.Equals(value) != true)) {
                    this.OperationIdField = value;
                    this.RaisePropertyChanged("OperationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Output {
            get {
                return this.OutputField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputField, value) != true)) {
                    this.OutputField = value;
                    this.RaisePropertyChanged("Output");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UnInstallDate {
            get {
                return this.UnInstallDateField;
            }
            set {
                if ((this.UnInstallDateField.Equals(value) != true)) {
                    this.UnInstallDateField = value;
                    this.RaisePropertyChanged("UnInstallDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Uninstalled {
            get {
                return this.UninstalledField;
            }
            set {
                if ((this.UninstalledField.Equals(value) != true)) {
                    this.UninstalledField = value;
                    this.RaisePropertyChanged("Uninstalled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdateDate {
            get {
                return this.UpdateDateField;
            }
            set {
                if ((this.UpdateDateField.Equals(value) != true)) {
                    this.UpdateDateField = value;
                    this.RaisePropertyChanged("UpdateDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogData", Namespace="http://schemas.datacontract.org/2004/07/CheckLicense.Log")]
    [System.SerializableAttribute()]
    public partial class LogData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ExpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FirmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LevelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LicenseController.autocad.masterkey.ws.LogDataType LogDataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReqXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LicenseController.autocad.masterkey.ws.LogDataState StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppName {
            get {
                return this.AppNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AppNameField, value) != true)) {
                    this.AppNameField = value;
                    this.RaisePropertyChanged("AppName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ExpId {
            get {
                return this.ExpIdField;
            }
            set {
                if ((this.ExpIdField.Equals(value) != true)) {
                    this.ExpIdField = value;
                    this.RaisePropertyChanged("ExpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FirmId {
            get {
                return this.FirmIdField;
            }
            set {
                if ((this.FirmIdField.Equals(value) != true)) {
                    this.FirmIdField = value;
                    this.RaisePropertyChanged("FirmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Host {
            get {
                return this.HostField;
            }
            set {
                if ((object.ReferenceEquals(this.HostField, value) != true)) {
                    this.HostField = value;
                    this.RaisePropertyChanged("Host");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LevelId {
            get {
                return this.LevelIdField;
            }
            set {
                if ((this.LevelIdField.Equals(value) != true)) {
                    this.LevelIdField = value;
                    this.RaisePropertyChanged("LevelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LicenseController.autocad.masterkey.ws.LogDataType LogDataType {
            get {
                return this.LogDataTypeField;
            }
            set {
                if ((this.LogDataTypeField.Equals(value) != true)) {
                    this.LogDataTypeField = value;
                    this.RaisePropertyChanged("LogDataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LogId {
            get {
                return this.LogIdField;
            }
            set {
                if ((this.LogIdField.Equals(value) != true)) {
                    this.LogIdField = value;
                    this.RaisePropertyChanged("LogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReqXml {
            get {
                return this.ReqXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.ReqXmlField, value) != true)) {
                    this.ReqXmlField = value;
                    this.RaisePropertyChanged("ReqXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResXml {
            get {
                return this.ResXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.ResXmlField, value) != true)) {
                    this.ResXmlField = value;
                    this.RaisePropertyChanged("ResXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LicenseController.autocad.masterkey.ws.LogDataState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogDataType", Namespace="http://schemas.datacontract.org/2004/07/CheckLicense.Log")]
    public enum LogDataType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InitiliazeProcess = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InitiliazeItemOfProcess = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateItemOfProcess = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UpdateProcess = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogDataState", Namespace="http://schemas.datacontract.org/2004/07/CheckLicense.Log")]
    public enum LogDataState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ControlPoint", Namespace="http://schemas.datacontract.org/2004/07/AutoCadLisansKontrol.DAL")]
    [System.SerializableAttribute()]
    public partial class ControlPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvgExecTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> WillCheckedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvgExecTime {
            get {
                return this.AvgExecTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AvgExecTimeField, value) != true)) {
                    this.AvgExecTimeField = value;
                    this.RaisePropertyChanged("AvgExecTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> WillChecked {
            get {
                return this.WillCheckedField;
            }
            set {
                if ((this.WillCheckedField.Equals(value) != true)) {
                    this.WillCheckedField = value;
                    this.RaisePropertyChanged("WillChecked");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Software", Namespace="http://schemas.datacontract.org/2004/07/LicenseControllerWs")]
    [System.SerializableAttribute()]
    public partial class Software : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppName {
            get {
                return this.AppNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AppNameField, value) != true)) {
                    this.AppNameField = value;
                    this.RaisePropertyChanged("AppName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FE_ControlList", Namespace="http://schemas.datacontract.org/2004/07/LicenseControllerWs")]
    [System.SerializableAttribute()]
    public partial class FE_ControlList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AppIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((this.AppIdField.Equals(value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Drive {
            get {
                return this.DriveField;
            }
            set {
                if ((object.ReferenceEquals(this.DriveField, value) != true)) {
                    this.DriveField = value;
                    this.RaisePropertyChanged("Drive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="autocad.masterkey.ws.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpsertFirm", ReplyAction="http://tempuri.org/IService1/UpsertFirmResponse")]
        void UpsertFirm(LicenseController.autocad.masterkey.ws.Firm firm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpsertFirm", ReplyAction="http://tempuri.org/IService1/UpsertFirmResponse")]
        System.Threading.Tasks.Task UpsertFirmAsync(LicenseController.autocad.masterkey.ws.Firm firm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFirm", ReplyAction="http://tempuri.org/IService1/GetFirmResponse")]
        LicenseController.autocad.masterkey.ws.Firm GetFirm(System.Nullable<int> firmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFirm", ReplyAction="http://tempuri.org/IService1/GetFirmResponse")]
        System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Firm> GetFirmAsync(System.Nullable<int> firmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListFirm", ReplyAction="http://tempuri.org/IService1/ListFirmResponse")]
        LicenseController.autocad.masterkey.ws.Firm[] ListFirm();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListFirm", ReplyAction="http://tempuri.org/IService1/ListFirmResponse")]
        System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Firm[]> ListFirmAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFirm", ReplyAction="http://tempuri.org/IService1/DeleteFirmResponse")]
        void DeleteFirm(int firmid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFirm", ReplyAction="http://tempuri.org/IService1/DeleteFirmResponse")]
        System.Threading.Tasks.Task DeleteFirmAsync(int firmid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateFirm", ReplyAction="http://tempuri.org/IService1/UpdateFirmResponse")]
        void UpdateFirm(LicenseController.autocad.masterkey.ws.Firm firm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateFirm", ReplyAction="http://tempuri.org/IService1/UpdateFirmResponse")]
        System.Threading.Tasks.Task UpdateFirmAsync(LicenseController.autocad.masterkey.ws.Firm firm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpsertComputer", ReplyAction="http://tempuri.org/IService1/UpsertComputerResponse")]
        int UpsertComputer(LicenseController.autocad.masterkey.ws.Computer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpsertComputer", ReplyAction="http://tempuri.org/IService1/UpsertComputerResponse")]
        System.Threading.Tasks.Task<int> UpsertComputerAsync(LicenseController.autocad.masterkey.ws.Computer c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOperation", ReplyAction="http://tempuri.org/IService1/GetOperationResponse")]
        LicenseController.autocad.masterkey.ws.Operation GetOperation(int opr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOperation", ReplyAction="http://tempuri.org/IService1/GetOperationResponse")]
        System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Operation> GetOperationAsync(int opr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListAllComputer", ReplyAction="http://tempuri.org/IService1/ListAllComputerResponse")]
        LicenseController.autocad.masterkey.ws.Computer[] ListAllComputer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListAllComputer", ReplyAction="http://tempuri.org/IService1/ListAllComputerResponse")]
        System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Computer[]> ListAllComputerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListComputer", ReplyAction="http://tempuri.org/IService1/ListComputerResponse")]
        LicenseController.autocad.masterkey.ws.Computer[] ListComputer(System.Nullable<int> firmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListComputer", ReplyAction="http://tempuri.org/IService1/ListComputerResponse")]
        System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Computer[]> ListComputerAsync(System.Nullable<int> firmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteComputer", ReplyAction="http://tempuri.org/IService1/DeleteComputerResponse")]
        void DeleteComputer(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteComputer", ReplyAction="http://tempuri.org/IService1/DeleteComputerResponse")]
        System.Threading.Tasks.Task DeleteComputerAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateComputer", ReplyAction="http://tempuri.org/IService1/UpdateComputerResponse")]
        void UpdateComputer(LicenseController.autocad.masterkey.ws.Computer comp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateComputer", ReplyAction="http://tempuri.org/IService1/UpdateComputerResponse")]
        System.Threading.Tasks.Task UpdateComputerAsync(LicenseController.autocad.masterkey.ws.Computer comp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpsertOperation", ReplyAction="http://tempuri.org/IService1/UpsertOperationResponse")]
        void UpsertOperation(LicenseController.autocad.masterkey.ws.Operation opr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpsertOperation", ReplyAction="http://tempuri.org/IService1/UpsertOperationResponse")]
        System.Threading.Tasks.Task UpsertOperationAsync(LicenseController.autocad.masterkey.ws.Operation opr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListAllOperation", ReplyAction="http://tempuri.org/IService1/ListAllOperationResponse")]
        LicenseController.autocad.masterkey.ws.Operation[] ListAllOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListAllOperation", ReplyAction="http://tempuri.org/IService1/ListAllOperationResponse")]
        System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Operation[]> ListAllOperationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListOperation", ReplyAction="http://tempuri.org/IService1/ListOperationResponse")]
        LicenseController.autocad.masterkey.ws.Operation[] ListOperation(int firmid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListOperation", ReplyAction="http://tempuri.org/IService1/ListOperationResponse")]
        System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Operation[]> ListOperationAsync(int firmid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOperation", ReplyAction="http://tempuri.org/IService1/DeleteOperationResponse")]
        void DeleteOperation(LicenseController.autocad.masterkey.ws.Operation opr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOperation", ReplyAction="http://tempuri.org/IService1/DeleteOperationResponse")]
        System.Threading.Tasks.Task DeleteOperationAsync(LicenseController.autocad.masterkey.ws.Operation opr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOperation", ReplyAction="http://tempuri.org/IService1/UpdateOperationResponse")]
        void UpdateOperation(LicenseController.autocad.masterkey.ws.Operation opr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOperation", ReplyAction="http://tempuri.org/IService1/UpdateOperationResponse")]
        System.Threading.Tasks.Task UpdateOperationAsync(LicenseController.autocad.masterkey.ws.Operation opr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpsertCheckLicense", ReplyAction="http://tempuri.org/IService1/UpsertCheckLicenseResponse")]
        void UpsertCheckLicense(LicenseController.autocad.masterkey.ws.CheckLicense oprdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpsertCheckLicense", ReplyAction="http://tempuri.org/IService1/UpsertCheckLicenseResponse")]
        System.Threading.Tasks.Task UpsertCheckLicenseAsync(LicenseController.autocad.masterkey.ws.CheckLicense oprdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogToDb", ReplyAction="http://tempuri.org/IService1/LogToDbResponse")]
        void LogToDb(LicenseController.autocad.masterkey.ws.LogData[] logs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogToDb", ReplyAction="http://tempuri.org/IService1/LogToDbResponse")]
        System.Threading.Tasks.Task LogToDbAsync(LicenseController.autocad.masterkey.ws.LogData[] logs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListCheckLicense", ReplyAction="http://tempuri.org/IService1/ListCheckLicenseResponse")]
        LicenseController.autocad.masterkey.ws.CheckLicense[] ListCheckLicense(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListCheckLicense", ReplyAction="http://tempuri.org/IService1/ListCheckLicenseResponse")]
        System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.CheckLicense[]> ListCheckLicenseAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCheckLicense", ReplyAction="http://tempuri.org/IService1/DeleteCheckLicenseResponse")]
        void DeleteCheckLicense(LicenseController.autocad.masterkey.ws.CheckLicense oprdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCheckLicense", ReplyAction="http://tempuri.org/IService1/DeleteCheckLicenseResponse")]
        System.Threading.Tasks.Task DeleteCheckLicenseAsync(LicenseController.autocad.masterkey.ws.CheckLicense oprdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCheckLicense", ReplyAction="http://tempuri.org/IService1/UpdateCheckLicenseResponse")]
        void UpdateCheckLicense(LicenseController.autocad.masterkey.ws.CheckLicense oprdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCheckLicense", ReplyAction="http://tempuri.org/IService1/UpdateCheckLicenseResponse")]
        System.Threading.Tasks.Task UpdateCheckLicenseAsync(LicenseController.autocad.masterkey.ws.CheckLicense oprdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAllComputerBaseFormid", ReplyAction="http://tempuri.org/IService1/DeleteAllComputerBaseFormidResponse")]
        void DeleteAllComputerBaseFormid(int firmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAllComputerBaseFormid", ReplyAction="http://tempuri.org/IService1/DeleteAllComputerBaseFormidResponse")]
        System.Threading.Tasks.Task DeleteAllComputerBaseFormidAsync(int firmId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAllLicenseBaseOperationid", ReplyAction="http://tempuri.org/IService1/DeleteAllLicenseBaseOperationidResponse")]
        void DeleteAllLicenseBaseOperationid(int oprId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAllLicenseBaseOperationid", ReplyAction="http://tempuri.org/IService1/DeleteAllLicenseBaseOperationidResponse")]
        System.Threading.Tasks.Task DeleteAllLicenseBaseOperationidAsync(int oprId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetControlPoint", ReplyAction="http://tempuri.org/IService1/GetControlPointResponse")]
        LicenseController.autocad.masterkey.ws.ControlPoint[] GetControlPoint();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetControlPoint", ReplyAction="http://tempuri.org/IService1/GetControlPointResponse")]
        System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.ControlPoint[]> GetControlPointAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllApplication", ReplyAction="http://tempuri.org/IService1/GetAllApplicationResponse")]
        LicenseController.autocad.masterkey.ws.Software[] GetAllApplication();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllApplication", ReplyAction="http://tempuri.org/IService1/GetAllApplicationResponse")]
        System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Software[]> GetAllApplicationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFEControlList", ReplyAction="http://tempuri.org/IService1/GetFEControlListResponse")]
        LicenseController.autocad.masterkey.ws.FE_ControlList[] GetFEControlList(int appid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFEControlList", ReplyAction="http://tempuri.org/IService1/GetFEControlListResponse")]
        System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.FE_ControlList[]> GetFEControlListAsync(int appid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetApplication", ReplyAction="http://tempuri.org/IService1/GetApplicationResponse")]
        LicenseController.autocad.masterkey.ws.Software GetApplication(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetApplication", ReplyAction="http://tempuri.org/IService1/GetApplicationResponse")]
        System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Software> GetApplicationAsync(System.Nullable<int> id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LicenseController.autocad.masterkey.ws.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LicenseController.autocad.masterkey.ws.IService1>, LicenseController.autocad.masterkey.ws.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpsertFirm(LicenseController.autocad.masterkey.ws.Firm firm) {
            base.Channel.UpsertFirm(firm);
        }
        
        public System.Threading.Tasks.Task UpsertFirmAsync(LicenseController.autocad.masterkey.ws.Firm firm) {
            return base.Channel.UpsertFirmAsync(firm);
        }
        
        public LicenseController.autocad.masterkey.ws.Firm GetFirm(System.Nullable<int> firmId) {
            return base.Channel.GetFirm(firmId);
        }
        
        public System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Firm> GetFirmAsync(System.Nullable<int> firmId) {
            return base.Channel.GetFirmAsync(firmId);
        }
        
        public LicenseController.autocad.masterkey.ws.Firm[] ListFirm() {
            return base.Channel.ListFirm();
        }
        
        public System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Firm[]> ListFirmAsync() {
            return base.Channel.ListFirmAsync();
        }
        
        public void DeleteFirm(int firmid) {
            base.Channel.DeleteFirm(firmid);
        }
        
        public System.Threading.Tasks.Task DeleteFirmAsync(int firmid) {
            return base.Channel.DeleteFirmAsync(firmid);
        }
        
        public void UpdateFirm(LicenseController.autocad.masterkey.ws.Firm firm) {
            base.Channel.UpdateFirm(firm);
        }
        
        public System.Threading.Tasks.Task UpdateFirmAsync(LicenseController.autocad.masterkey.ws.Firm firm) {
            return base.Channel.UpdateFirmAsync(firm);
        }
        
        public int UpsertComputer(LicenseController.autocad.masterkey.ws.Computer c) {
            return base.Channel.UpsertComputer(c);
        }
        
        public System.Threading.Tasks.Task<int> UpsertComputerAsync(LicenseController.autocad.masterkey.ws.Computer c) {
            return base.Channel.UpsertComputerAsync(c);
        }
        
        public LicenseController.autocad.masterkey.ws.Operation GetOperation(int opr) {
            return base.Channel.GetOperation(opr);
        }
        
        public System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Operation> GetOperationAsync(int opr) {
            return base.Channel.GetOperationAsync(opr);
        }
        
        public LicenseController.autocad.masterkey.ws.Computer[] ListAllComputer() {
            return base.Channel.ListAllComputer();
        }
        
        public System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Computer[]> ListAllComputerAsync() {
            return base.Channel.ListAllComputerAsync();
        }
        
        public LicenseController.autocad.masterkey.ws.Computer[] ListComputer(System.Nullable<int> firmId) {
            return base.Channel.ListComputer(firmId);
        }
        
        public System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Computer[]> ListComputerAsync(System.Nullable<int> firmId) {
            return base.Channel.ListComputerAsync(firmId);
        }
        
        public void DeleteComputer(int Id) {
            base.Channel.DeleteComputer(Id);
        }
        
        public System.Threading.Tasks.Task DeleteComputerAsync(int Id) {
            return base.Channel.DeleteComputerAsync(Id);
        }
        
        public void UpdateComputer(LicenseController.autocad.masterkey.ws.Computer comp) {
            base.Channel.UpdateComputer(comp);
        }
        
        public System.Threading.Tasks.Task UpdateComputerAsync(LicenseController.autocad.masterkey.ws.Computer comp) {
            return base.Channel.UpdateComputerAsync(comp);
        }
        
        public void UpsertOperation(LicenseController.autocad.masterkey.ws.Operation opr) {
            base.Channel.UpsertOperation(opr);
        }
        
        public System.Threading.Tasks.Task UpsertOperationAsync(LicenseController.autocad.masterkey.ws.Operation opr) {
            return base.Channel.UpsertOperationAsync(opr);
        }
        
        public LicenseController.autocad.masterkey.ws.Operation[] ListAllOperation() {
            return base.Channel.ListAllOperation();
        }
        
        public System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Operation[]> ListAllOperationAsync() {
            return base.Channel.ListAllOperationAsync();
        }
        
        public LicenseController.autocad.masterkey.ws.Operation[] ListOperation(int firmid) {
            return base.Channel.ListOperation(firmid);
        }
        
        public System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Operation[]> ListOperationAsync(int firmid) {
            return base.Channel.ListOperationAsync(firmid);
        }
        
        public void DeleteOperation(LicenseController.autocad.masterkey.ws.Operation opr) {
            base.Channel.DeleteOperation(opr);
        }
        
        public System.Threading.Tasks.Task DeleteOperationAsync(LicenseController.autocad.masterkey.ws.Operation opr) {
            return base.Channel.DeleteOperationAsync(opr);
        }
        
        public void UpdateOperation(LicenseController.autocad.masterkey.ws.Operation opr) {
            base.Channel.UpdateOperation(opr);
        }
        
        public System.Threading.Tasks.Task UpdateOperationAsync(LicenseController.autocad.masterkey.ws.Operation opr) {
            return base.Channel.UpdateOperationAsync(opr);
        }
        
        public void UpsertCheckLicense(LicenseController.autocad.masterkey.ws.CheckLicense oprdetail) {
            base.Channel.UpsertCheckLicense(oprdetail);
        }
        
        public System.Threading.Tasks.Task UpsertCheckLicenseAsync(LicenseController.autocad.masterkey.ws.CheckLicense oprdetail) {
            return base.Channel.UpsertCheckLicenseAsync(oprdetail);
        }
        
        public void LogToDb(LicenseController.autocad.masterkey.ws.LogData[] logs) {
            base.Channel.LogToDb(logs);
        }
        
        public System.Threading.Tasks.Task LogToDbAsync(LicenseController.autocad.masterkey.ws.LogData[] logs) {
            return base.Channel.LogToDbAsync(logs);
        }
        
        public LicenseController.autocad.masterkey.ws.CheckLicense[] ListCheckLicense(int id) {
            return base.Channel.ListCheckLicense(id);
        }
        
        public System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.CheckLicense[]> ListCheckLicenseAsync(int id) {
            return base.Channel.ListCheckLicenseAsync(id);
        }
        
        public void DeleteCheckLicense(LicenseController.autocad.masterkey.ws.CheckLicense oprdetail) {
            base.Channel.DeleteCheckLicense(oprdetail);
        }
        
        public System.Threading.Tasks.Task DeleteCheckLicenseAsync(LicenseController.autocad.masterkey.ws.CheckLicense oprdetail) {
            return base.Channel.DeleteCheckLicenseAsync(oprdetail);
        }
        
        public void UpdateCheckLicense(LicenseController.autocad.masterkey.ws.CheckLicense oprdetail) {
            base.Channel.UpdateCheckLicense(oprdetail);
        }
        
        public System.Threading.Tasks.Task UpdateCheckLicenseAsync(LicenseController.autocad.masterkey.ws.CheckLicense oprdetail) {
            return base.Channel.UpdateCheckLicenseAsync(oprdetail);
        }
        
        public void DeleteAllComputerBaseFormid(int firmId) {
            base.Channel.DeleteAllComputerBaseFormid(firmId);
        }
        
        public System.Threading.Tasks.Task DeleteAllComputerBaseFormidAsync(int firmId) {
            return base.Channel.DeleteAllComputerBaseFormidAsync(firmId);
        }
        
        public void DeleteAllLicenseBaseOperationid(int oprId) {
            base.Channel.DeleteAllLicenseBaseOperationid(oprId);
        }
        
        public System.Threading.Tasks.Task DeleteAllLicenseBaseOperationidAsync(int oprId) {
            return base.Channel.DeleteAllLicenseBaseOperationidAsync(oprId);
        }
        
        public LicenseController.autocad.masterkey.ws.ControlPoint[] GetControlPoint() {
            return base.Channel.GetControlPoint();
        }
        
        public System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.ControlPoint[]> GetControlPointAsync() {
            return base.Channel.GetControlPointAsync();
        }
        
        public LicenseController.autocad.masterkey.ws.Software[] GetAllApplication() {
            return base.Channel.GetAllApplication();
        }
        
        public System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Software[]> GetAllApplicationAsync() {
            return base.Channel.GetAllApplicationAsync();
        }
        
        public LicenseController.autocad.masterkey.ws.FE_ControlList[] GetFEControlList(int appid) {
            return base.Channel.GetFEControlList(appid);
        }
        
        public System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.FE_ControlList[]> GetFEControlListAsync(int appid) {
            return base.Channel.GetFEControlListAsync(appid);
        }
        
        public LicenseController.autocad.masterkey.ws.Software GetApplication(System.Nullable<int> id) {
            return base.Channel.GetApplication(id);
        }
        
        public System.Threading.Tasks.Task<LicenseController.autocad.masterkey.ws.Software> GetApplicationAsync(System.Nullable<int> id) {
            return base.Channel.GetApplicationAsync(id);
        }
    }
}
