//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCadLisansKontrol.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AUTOCADLICENSEEntities1 : DbContext
    {
        public AUTOCADLICENSEEntities1()
            : base("name=AUTOCADLICENSEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Computer> Computer { get; set; }
        public virtual DbSet<Firm> Firm { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<OperationDetail> OperationDetail { get; set; }
    }
}
