//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCadLisansKontrol.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AUTOCADLICENSEEntities1 : DbContext
    {
        public AUTOCADLICENSEEntities1()
            : base("name=AUTOCADLICENSEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckLicenseEntity> CheckLicense { get; set; }
        public virtual DbSet<ComputerEntity> Computer { get; set; }
        public virtual DbSet<FirmEntity> Firm { get; set; }
        public virtual DbSet<OperationEntity> Operation { get; set; }
    
        public virtual int SP_DELETE_COMPUTER(Nullable<int> fIRMID)
        {
            var fIRMIDParameter = fIRMID.HasValue ?
                new ObjectParameter("FIRMID", fIRMID) :
                new ObjectParameter("FIRMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_COMPUTER", fIRMIDParameter);
        }
    
        public virtual int SP_DELETE_FIRM(Nullable<int> fIRMID)
        {
            var fIRMIDParameter = fIRMID.HasValue ?
                new ObjectParameter("FIRMID", fIRMID) :
                new ObjectParameter("FIRMID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_FIRM", fIRMIDParameter);
        }
    
        public virtual int SP_DELETE_OPERATION(Nullable<int> oPRID)
        {
            var oPRIDParameter = oPRID.HasValue ?
                new ObjectParameter("OPRID", oPRID) :
                new ObjectParameter("OPRID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DELETE_OPERATION", oPRIDParameter);
        }
    }
}
