//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCadLisansKontrol.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckLicenseEntity
    {
        public int Id { get; set; }
        public Nullable<int> ComputerId { get; set; }
        public string Output { get; set; }
        public Nullable<int> IsUnlicensed { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> OperationId { get; set; }
    
        public virtual OperationEntity Operation { get; set; }
    }
}
