//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCadLisansKontrol.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FE_ControlListEntity
    {
        public int Id { get; set; }
        public string Drive { get; set; }
        public string Path { get; set; }
        public string Type { get; set; }
        public Nullable<int> AppId { get; set; }
    
        public virtual SoftwareEntity Software { get; set; }
    }
}
